theme: jekyll-theme-cayman
title: Welcome to Nafees Qamar's homepage!
About me: I am Dr. Nafees Qamar, working as an Assistant Professor at the University of Hafr Al-Batin (formerly a KFUPM campus), KSA. Prior to joining this university, I worked as Postdoctoral Research Scholar at Vanderbilt University, United States. I hold a PhD in Computer Science from INRIA, Grenoble France. 
